##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by dev-cetera.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: Prepare Release Version

## -----------------------------------------------------------------------------

on:
  push:
    branches:
      - main

## -----------------------------------------------------------------------------

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the full repository history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Get the first line of the latest commit message
      - name: Get commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1 HEAD | head -n 1)
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_OUTPUT

      # Step 3: Check for release trigger
      - name: Check for release trigger
        id: check_message
        run: |
          if [[ "${{ steps.get_commit.outputs.COMMIT_MSG }}" == +* ]]; then
            echo "PROCEED=true" >> $GITHUB_OUTPUT
            echo "Release triggered by '+' commit."
          else
            echo "PROCEED=false" >> $GITHUB_OUTPUT
            echo "Standard commit. No release action taken."
          fi

      # --- The following steps only run if the release is triggered ---

      - name: Set up Dart
        if: steps.check_message.outputs.PROCEED == 'true'
        uses: dart-lang/setup-dart@v1

      # NEW: Fetch the central README template from its own repository
      - name: Fetch README Template
        if: steps.check_message.outputs.PROCEED == 'true'
        run: |
          git clone --depth 1 https://github.com/dev-cetera/dart_package_template.git /tmp/dart_package_template
          echo "TEMPLATE_PATH=/tmp/dart_package_template/_README_TEMPLATE.md" >> $GITHUB_ENV

      - name: Format and Fix Dart Code
        if: steps.check_message.outputs.PROCEED == 'true'
        run: |
          dart format .
          dart fix --apply

      # ENHANCED: Extracts both version and name now
      - name: Extract package info from pubspec.yaml
        if: steps.check_message.outputs.PROCEED == 'true'
        id: get_package_info
        run: |
          VERSION=$(grep "version:" pubspec.yaml | sed 's/version: //')
          PACKAGE_NAME=$(grep "name:" pubspec.yaml | sed 's/name: //')
          echo "PUBSPEC_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG.md
        if: steps.check_message.outputs.PROCEED == 'true'
        run: |
          RELEASE_NOTES=$(echo "${{ steps.get_commit.outputs.COMMIT_MSG }}" | sed 's/^+//')
          dart run .github/scripts/update_changelog.dart "${{ steps.get_package_info.outputs.PUBSPEC_VERSION }}" "$RELEASE_NOTES"

      # NEW: Generate the README.md file using a Dart script
      - name: Generate README.md
        if: steps.check_message.outputs.PROCEED == 'true'
        run: |
          # This script is dependency-free, so no 'pub get' is needed.
          dart run .github/scripts/update_readme.dart "${{ env.TEMPLATE_PATH }}" "${{ steps.get_package_info.outputs.PACKAGE_NAME }}" "${{ steps.get_package_info.outputs.PUBSPEC_VERSION }}"

      - name: Commit all automated changes
        if: steps.check_message.outputs.PROCEED == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "ci: bump version to v${{ steps.get_package_info.outputs.PUBSPEC_VERSION }}"
          else
            echo "No changes to commit."
          fi

      - name: Force-Create and Push Git Tag
        if: steps.check_message.outputs.PROCEED == 'true'
        run: |
          TAG_NAME="v${{ steps.get_package_info.outputs.PUBSPEC_VERSION }}"
          git push --delete origin "$TAG_NAME" || true
          git tag -a -f "$TAG_NAME" -m "Release version ${TAG_NAME}"
          git push origin "$TAG_NAME"
          echo "Successfully created or replaced tag ${TAG_NAME}."

      - name: Push automated commit
        if: steps.check_message.outputs.PROCEED == 'true'
        run: |
          git pull --rebase
          git push origin main